# Generated by Django 3.2.9 on 2023-11-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=3000)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('URGENT', 'Urgent'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=8)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('URGENT', 'Urgent'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=3000, null=True)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.issue')),
            ],
        ),
    ]
