# Generated by Django 3.2.9 on 2023-11-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='IssueHistory',
        ),
        migrations.RenameModel(
            old_name='Machine',
            new_name='MachineDetail',
        ),
    ]
