# Generated by Django 3.2.9 on 2023-11-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20231123_0520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineDetail',
            new_name='Detail',
        ),
    ]
