# Generated by Django 3.2.9 on 2023-11-23 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_rename_machinedetail_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
