# Generated by Django 3.2.9 on 2023-11-23 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_issue_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='machine.detail'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timestamp_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
